name: Tests

on:
  push:
  pull_request:
  # Allows running this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  test:
    strategy:
      # When fail-fast is true, one failure cancels all matrix.
      fail-fast: false
      matrix:
        smalltalk: [ Pharo64-9.0, Pharo64-10, Pharo64-11 ]
        os: [ ubuntu-latest, macos-latest, windows-latest ]
        ston: [ .ci.ston ]
    runs-on: ${{ matrix.os }}
    name: ${{ matrix.smalltalk }} on ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: Setup smalltalkCI
        uses: hpi-swa/setup-smalltalkCI@v1
        with:
          smalltalk-image: ${{ matrix.smalltalk }}
      - name: Load Image and Run Tests
        run: smalltalkci -s ${{ matrix.smalltalk }} ${{ matrix.ston }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        timeout-minutes: 10
